name: build 

on: 
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
        
      - name: depts
        run: | 
         sudo apt-get update
         sudo apt-get install -y --no-install-recommends \
         libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-gfx-dev \
         libgtk-3-dev

      - name: build 
        run: go build ./...


      
  appimage:
    needs: check
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: build container
        run: docker build -t exnes-build -f build/Dockerfile .

      - name: build Image 
        run: docker run --rm -v "$PWD:/src" -u "$(id -u):$(id -g)" -e HOME=/tmp -e GOCACHE=/tmp/go-build -e GOMODCACHE=/tmp/go-mod exnes-build ./build/AppImage.sh

      - uses: softprops/action-gh-release@v2
        with: 
          files: dist/*.AppImage

  

